---
- name: Gather security rules
  hosts: palo_firewall
  connection: httpapi
  gather_facts: false

  vars:
    device:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"

  tasks:
    - name: Get all security rules
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        gathered_filter: "*"
        state: gathered
      register: sec_rules

    - name: Output
      ansible.builtin.debug:
        msg: "{{ sec_rules.gathered }}"

    - name: Output rule names
      ansible.builtin.debug:
        msg: "List of rules {{ sec_rules.gathered | map(attribute='rule_name') | list }}"

