---
- name: Create Address Object in Palo Alto via Ansible
  hosts: palo_firewall
  connection: httpapi
  gather_facts: false
  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      api_key: " {{ api_key }} "
  tasks:
    - name: Commit candidate configs on firewall
      paloaltonetworks.panos.panos_commit_firewall:
        provider: '{{ provider }}'
