---
- name: Create Address Object in Palo Alto via Ansible
  hosts: pa_fws
  connection: httpapi
  gather_facts: false
  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
  tasks:
    - name: Commit candidate configs on firewall
      paloaltonetworks.panos.panos_commit_firewall:
        provider: '{{ provider }}'
