---
- name: Show system status on Palo Alto Firewall via HTTPAPI with username/password
  hosts: pa_fws
  gather_facts: no
  connection: httpapi
  collections:
    - paloaltonetworks.panos
  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"

  tasks:
    - name: Get the system info
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: show system info
      register: res

    - name: Show the system info
      ansible.builtin.debug:
        msg: "{{ res.stdout }}"
