---
- name: Gather system info
  hosts: palo_firewall
  connection: httpapi
  tasks:
    - name: Gather facts for device
      paloaltonetworks.panos.panos_facts:
        provider: "{{ device }}"

    - name: Display information
      ansible.builtin.debug:
        msg:
          - "Hostname: {{ ansible_facts.net_hostname }}"
          - "Serial: {{ ansible_facts.net_serial }}"
          - "Model: {{ ansible_facts.net_model }}"
          - "Version: {{ ansible_facts.net_version }}"
          - "Uptime: {{ ansible_facts.net_uptime }}"
          - "CPU Usage: {{ ansible_facts.net_cpu_usage }}"
          - "Memory Usage: {{ ansible_facts.net_mem_usage }}"
          - "Session Usage: {{ ansible_facts.net_session_usage }} / {{ ansible_facts.net_session_max }}"
