---
- name: Create Address Object in Palo Alto via Ansible
  hosts: palo_firewall
  connection: httpapi
  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      api_key: "{{ api_key }}"
  tasks:
    - name: Get facts
      paloaltonetworks.panos.panos_facts:
        provider: "{{ provider }}"
        gather_subset: ['config']
      register: result

    - name: Save info to file
      local_action:
        module: copy
        content: "{{ result }}"
        dest: ./panos_info.txt