---
- name: Create Address Object in Palo Alto via Ansible
  hosts: palo_firewall
  connection: httpapi
  gather_facts: false
  vars_prompt:
    - name: "object_name"
      prompt: "Enter the name of the address object to delete"
      private: false
  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      api_key: " {{ api_key }} "
  tasks:
    - name: Delete address object
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ provider }}"
        name: "{{ object_name }}"
        state: absent