---
- name: Gather security rules
  hosts: paloalto_fw01
  connection: httpapi

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:
    - name: Get all security rules
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        gathered_filter: "*"
        state: gathered
      register: sec_rules

    - name: Output
      ansible.builtin.debug:
        msg: "{{ sec_rules }}"