---
- name: Gather security rules
  hosts: palo_firewall
  connection: httpapi
  gather_facts: false

  vars_prompt:
    - name: "target_rule_name"
      prompt: "Please enter the rule name:"
      private: false  # Set to 'yes' if you want the input to be hidden

  vars:
    device:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"

  tasks:
    - name: Get all security rules
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        gathered_filter: "*"
        state: gathered
      register: sec_rules

    - name: Output UUID for specific rule
      ansible.builtin.debug:
        msg: >
          "UUID of requested rule {{ target_rule_name }} is:
          {{ (sec_rules.gathered | selectattr('rule_name', 'equalto', target_rule_name) | map(attribute='uuid') | list) }}"