---
- name: Create Address Object in Palo Alto via Ansible
  hosts: pa_fws
  connection: httpapi
  gather_facts: false
  
  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
  tasks:
    - name: Create address object
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ provider }}"
        name: "{{ object_name }}"
        value: "{{ object_ip }}"
        address_type: "{{ address_type }}"
        description: "{{ object_description }}"
