---
- name: Show system status on Palo Alto Firewall via HTTPAPI with username/password
  hosts: pa_fws
  gather_facts: no
  connection: httpapi
  collections:
    - paloaltonetworks.panos
  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
  tasks:
    - name: Run 'show system state' command via API
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: show system state
      register: system_state_output

    - name: Show system state output raw
      debug:
        var: system_state_output.stdout

    - name: Parse system state output JSON string
      set_fact:
        parsed_output: "{{ system_state_output.stdout | from_json }}"

    - name: Show system state output prettified
      debug:
        msg: "{{ parsed_output | to_nice_json }}"

    - name: Extract software version
      debug:
        msg: "Software Version: {{ parsed_output.response.result['local.sw_version'] }}"

    - name: Extract model and sw_version using json_query
      set_fact:
        palo_info: "{{ parsed_output | json_query('response.result.local.{model: model, sw_version: sw_version}') }}"

    - name: Display model and software version
      debug:
        msg: "Model: {{ palo_info.model }}, Software Version: {{ palo_info.sw_version }}"
