---
- name: Run 'show system state' via CLI using panos_op
  hosts: pa_fws
  gather_facts: no
  collections:
    - paloaltonetworks.panos
  vars:
    ansible_network_os: paloaltonetworks.panos.panos
    ansible_connection: network_cli
  tasks:
    - name: Run system state command
      panos_op:
        cmd: show system state
      register: output

    - name: Show output
      debug:
        var: output.stdout
