---

- name: Show system status on Palo Alto Firewall via HTTPAPI with username/password
  hosts: pa_fws
  gather_facts: no
  collections:
    - paloaltonetworks.panos
  vars:
    ansible_network_os: paloaltonetworks.panos
    ansible_connection: httpapi
  tasks:
    - name: Run 'show system state' command via API
      panos_op:
        cmd: show system state
      register: system_state_output

    - name: Show system state output
      debug:
        var: system_state_output.stdout


