---
- name: Run show system state using CLI
  hosts: paloalto_devices
  gather_facts: false
  collections:
    - paloaltonetworks.panos
  vars:
    ansible_network_os: paloaltonetworks.panos.panos
    ansible_connection: network_cli
  tasks:
    - panos_cli:
        cli: show system state
      register: output

    - debug:
        var: output.stdout_lines
