---
- name: Show system state on Palo Alto Firewall
  hosts: pa_fws
  gather_facts: no
  collections:
    - paloaltonetworks.panos
  vars:
    ansible_network_os: paloaltonetworks.panos.panos
    ansible_connection: network_cli
  tasks:
    - name: Get system state
      panos_op:
        cmd: show system state
      register: system_state_output

    - name: Display system state output
      debug:
        var: system_state_output.stdout
