---
- name: Get system status on Palo Alto Firewall
  hosts: pa_fws
  gather_facts: false
  collections:
    - paloaltonetworks.panos
  vars:
    ansible_network_os: paloaltonetworks.panos
    ansible_connection: network_cli
  tasks:
    - name: Run show system state command
      panos_op:
        cmd: show system state
      register: system_state

    - name: Display output
      debug:
        var: system_state.stdout

