- hosts: pa_fws
  gather_facts: no
  connection: httpapi
  collections:
    - paloaltonetworks.panos
  vars:
    ansible_network_os: paloaltonetworks.panos
  tasks:
    - paloaltonetworks.panos.panos_op:
        cmd: show system state
      register: output

    - debug:
        var: output.stdout
