---
- name: Gather system info
  hosts: pa_fws
  connection: httpapi
  gather_facts: false
  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      
  tasks:
    - name: Get system facts
      paloaltonetworks.panos.panos_facts:
        provider: "{{ provider }}"
        gather_subset: ['all']
      register: panos_data
    
    - name: Show CPU usage
      debug:
        msg: 
          - "Hostname: {{ ansible_net_hostname }}"
          - "Version: {{ ansible_net_version }}"
          - "MgmtIP: {{ provider.ip_address}}"

