---
- name: Gather system info
  hosts: pa_fws
  connection: httpapi
  gather_facts: false
  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      
  tasks:
    - name: Get system facts (CPU and session count)
      paloaltonetworks.panos.panos_facts:
        provider: "{{ provider }}"
        gather_subset:
          - system
          - interfaces
      register: panos_data
    
    - name: Show CPU usage
      debug:
        msg: 
          - "Hostname: {{ panos_data.system.ansible_net_hostname }}"

