---
- name: Gather system info
  hosts: pa_fws
  connection: httpapi
  gather_facts: false
  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      
  tasks:
    - name: Gather facts for device
      paloaltonetworks.panos.panos_facts:
        provider: "{{ provider }}"
        gather_subset:
          - system
      register: panos_data

    - name: Inspect full output structure
      debug:
        var: panos_data

    - name: Show CPU usage only
      debug:
        msg: "CPU usage: {{ panos_data.system_info.cpu_usage }}"
